### ISSUE TITLE
converting to non-pointer type 'int' from NULL in GfxUi.cpp

### ISSUE THREAD

**Issue by awumaker** [squix78/esp8266-weather-station-color#12]
It seems, that SPIFFS.open(filename, "r") returns 0 and not NULL, if it can't find the file.

At least my compiler gives me a WARNING:

src\GfxUi.cpp: In member function 'void GfxUi::drawBmp(String, uint8_t, uint16_t)':
src\GfxUi.cpp:107:49: warning: converting to non-pointer type 'int' from NULL [-Wconversion-null]
if ((bmpFile = SPIFFS.open(filename, "r")) == NULL) {
^

and when I change it to:

  if ((bmpFile = SPIFFS.open(filename, "r")) == 0){
    Serial.print(F("File not found"));
    return;
  }

the compiler is happy and shows no WARNING.

Maybe it helps, to get the code with a warning less...

**Comment by squix78** [comment]
This part of the code has been removed with the new version based on the MiniGrafx library. Do you agree that we can close this issue?

**Comment by squix78** [comment]
Closing due to no response after one week
