### ISSUE TITLE
Save images locally

### ISSUE THREAD

**Issue by AFUDIrk** [squix78/esp8266-weather-station-color#16]
Hello, the display ILI9341 has a slot for an SD card. If you can not use this option,
To put the images for the weather and the moon phases there?
Then they do not need to be loaded from the Internet every time.

greeting
Dirk

**Comment by KarlNorway** [comment]
They are only downloaded if the are not present in SPIFF

26. mai 2017 9:12 a.m. skrev "Dirk" <notifications@github.com>:

**Comment by G6EJD** [comment]
You could use the isplays SD card, but the additional wiring and need for another data pin for SD card chip-select makes using the on-board storage an elegant solution especially as the chip's flash storage is ample and generally unused.

**Comment by AFUDIrk** [comment]
True, in the new version, the images are stored in the SPIFF and it works. It has only a small error, at chancetstorms.bmp not chancestorms and the folder under recourses must be mini and not small.
