### ISSUE TITLE
WiFi will not connect for the Color model

### ISSUE THREAD

**Issue by sonofcy** [squix78/esp8266-weather-station-color#170]
Use one of the two templates below and delete the rest.

8<------------------------ BUG REPORT -----------------------------------------
### Expected behavior
WiFi should connect
### Actual behavior
Wifi Status is  WL_STATUS 7 forever
### Test code
Reduce the HOSTNAME from 32 chars to at least 1 less.

```c
// add code here
#define WIFI_HOSTNAME "ThingPulseWeatherStationColor"
```
### Weather Station Color version
Which branch are you on? If you know the Git revision then add it here as well.
I don't know

### Hardware
Describe whether you run the code on the ThingPulse Weather Station Color kit or on some custom hardware.
I am using the ThingPulse Weather Station Color kit 

8<------------------------ END BUG REPORT -------------------------------------

8<------------------------ FEATURE REQUEST ------------------------------------
### Justification
Tell us why you would like to see this feature added.

### Workarounds
Are there any workarounds you currently have in place because the feature is missing?

8<------------------------ END FEATURE REQUEST --------------------------------

**Comment by marcelstoer** [comment]
Thanks. Here they state that the max be 32 chars: https://arduino-esp8266.readthedocs.io/en/3.1.2/esp8266wifi/station-class.html#hostname

**Comment by sonofcy** [comment]
Yes, 32 CHARS, NOT a String of 32 (33rd will be /00)
