### ISSUE TITLE
Carousel.h ?

### ISSUE THREAD

**Issue by djuscha** [squix78/esp8266-weather-station-color#20]
Where can I download Carousel.h?

**Comment by squix78** [comment]
You should get it automatically by installing MiniGrafx (
https://github.com/squix78/minigrafx). Either through the library manager
in the arduino ide or by downloading the zip and installing it manually.

Please let me know if we can close this issue...

2017-07-03 21:24 GMT+02:00 djuscha <notifications@github.com>:

**Comment by djuscha** [comment]
It has worked. Thanks!

**Comment by squix78** [comment]
From your comment I assume that I can close this issue. Otherwise please re-open it.
