### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by Trecoolius** [squix78/esp8266-weather-station-color#21]
```
esp8266-weather-station-color:524: error: 'class MiniGrafx' has no member named 'drawStringMaxWidth'

   gfx.drawStringMaxWidth(15, 265, 240 - 2 * 15, ESP.getResetInfo());

       ^


exit status 1
'class MiniGrafx' has no member named 'drawStringMaxWidth'
```

**Comment by squix78** [comment]
Please update the MiniGrafx library to version 0.0.11. It could be that the
Arduino IDE library manager does not offer this version yet from the drop
down. Then either wait and check back or download the library from the
github repository manually and replace the already installed version:
https://github.com/squix78/minigrafx

Please close this issue if you agree that the library update solves it

Thank you
Daniel

2017-07-10 7:04 GMT+02:00 Trecoolius <notifications@github.com>:

**Comment by Trecoolius** [comment]
That did it, thanks.
