### ISSUE TITLE
WiFi credentials

### ISSUE THREAD

**Issue by floresta** [squix78/esp8266-weather-station-color#26]
Hi Daniel

It seems that in the process of enhancing your program one of the basics may have slipped through the cracks.

Just curious why the WiFi credentials (SSID and Password) aren't specified in settings.h or by definitions at the top of the .ino file?  

To get connected I had to scroll down to line 166 of the .ino file and enter those credentials.  Did I miss something?

Don

**Comment by squix78** [comment]
Hi Don

Thanks so much for pointing this out. I just committed a fix. Can you close this issue if you agree?

Daniel

**Comment by floresta** [comment]
Looks good to me!  I also learned how to close an issue.

Don
