### ISSUE TITLE
Time source

### ISSUE THREAD

**Issue by k5map** [squix78/esp8266-weather-station-color#3]
After reviewing the code, am I correct in you are using Weather Underground as the time source for the clock being displayed?

**Comment by KarlNorway** [comment]
I have also noticed this in the code. From what I can tell from the output from WG the time you get is based on what location you have set. ( I have tried several locations around the world to conclude with this)

**Comment by squix78** [comment]
I believe this has been fixed in the new version of the weather station by using the built in NTP module. Can you please confirm and close this issue if you agree?

**Comment by squix78** [comment]
Closing due to no response after one week
