### ISSUE TITLE
Sketch does not run

### ISSUE THREAD

**Issue by ericklil** [squix78/esp8266-weather-station-color#37]
Hello, after installing on your WiFi Color Display `Kit` the sketch hangs her:

```
[HTTP] GET... code: 200
start document
[HTTP] GET...
[HTTP] GET... code: 200
start document

DST Rules Updated:
DST Start: Sun Mar 12 02:00:00 2017
DST End:   Sun Nov 05 01:00:00 2017
```

Screen displays nothing has a slight flicker ( also when plugged in to adequate power supply)
Any ideas would be welcomed..

Great project though!!

**Comment by squix78** [comment]
Did you already have a look at questions and solutions here:
https://support.squix.org

**Comment by ericklil** [comment]
Thanks Daniel,

i did but did not see a similar issue. i have to admit however that I did not read all posts and answers…
any input would be greatly appreciated ( all  samples run fine)

  Erick Oeseburg
       Encinitas
       92024 CA
  +1 (619) 988-1543
poolworks@mac.com

**Comment by ericklil** [comment]
Sorry my bad some connections were not soldered properly....Thanks for your help!
