### ISSUE TITLE
Software Requirements/ Libraries

### ISSUE THREAD

**Issue by aliceand** [squix78/esp8266-weather-station-color#4]
Please add Json Streaming Parser (by Daniel Eichhorn) to the list of required libraries in the esp8266-weather-station-color project.

Please continue your awesome work. I have some personal projects based on them I use everyday.

**Comment by squix78** [comment]
Thank you for the input. I have added the library. Do you agree? Please confirm and close this issue.

**Comment by squix78** [comment]
Closing due to no response after one week
