### ISSUE TITLE
Source Code for Weatherstation without Touch

### ISSUE THREAD

**Issue by ClashC** [squix78/esp8266-weather-station-color#51]
I bought the variation without touch. 
Where can I get the source code?

**Comment by lorol** [comment]
What did you buy and where?

**Comment by ClashC** [comment]
Sorry, i mean the fork from @cxandy, sorry. https://github.com/cxandy/esp8266-weather-station-color
I have buy from alieexpress ( https://de.aliexpress.com/store/product/Esp8266-wetterstation-color-240x320-display-wunderground-open-source-github-AZSMZ-TFT-TOUCH/2179173_32836372386.html )

Should I delete the issue?
